version: '3.8'

services:
  server:
    build: ./server
    container_name: fitflow-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:                         
      - ./server/uploads:/app/uploads 
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/test', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  client:
    build: ./client
    container_name: fitflow-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy

volumes:
  mongodb_data: